import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header/Header'
import Slider from '../components/UI/Slider/Slider'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Slider sliderData={[
        {
          id: 0,
          title: 'Ого, заголовок!',
          subtitle: 'Ого, это подзаголовок.'
        },
        {
          id: 1,
          title: 'Ого, второй заголовок!',
          subtitle: 'Ого, это ещё подзаголовок.'
        },
        {
          id: 2,
          title: 'Ого, третий заголовок!',
          subtitle: 'Ого, это ещё подзаголовок.'
        },
      ]}
      />
    </>
  )
}

export default Home
